import GlobalProvider from "@/components/Application/GlobalProvider";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Assistant, Geist } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "StepUp Shoes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        assistantFont.className,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <GlobalProvider>
          <TooltipProvider>
            <ToastContainer />
            {children}
          </TooltipProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
